# Matching GitHub users to Slack users
a-afsharfarnia: U02C97YAQDN
akosbeke: U02S1QSDW01
aleksandarstojsin: UK1PGSHGV
alxmiron: U02FSCJLSHF
annroz: U02F9UXTEGJ
AnthonyDrew94: U024DN0P8LD
balazscsaba2006: UNKJMJTPV
ChristianHaeckh: U024A1DKWUE
chrstph-dvx: U02MW885Q3X
dependabot: U9TH7PNRY
'dependabot[bot]': U9TH7PNRY
DespinaA: UJ7676T9B
dioxmio: UA40QBGAW
Diroro: U02UBPGC7V5
fseker: U02FA071KPV
genesy: U01BN6Q9ACE
hgimenez: U01BE6F361M
iulianadrg: U0293J3TFGD
januszmk: U02NXN0QNA2
jonnybel: U02E9PUS40H
kamilkrajnik: U02KQ5QSF2S
khanilov: U02P5012GTD
krichard12: U029YLS7RGR
lisovskyvlad: U022AQ24U8N
matleve98: U02F4EU8L9Y
mericsferenc: U02HULF4H4Z
michealmouner: UEKFUKJ59
gehadMohamed: U02V3LFMXLP
mstockd: U1WTTS3PT
Pelyko: U0273E73D6X
picur: U01HETXKN4A
rasheedhamdawi: UHH050M36
santistebanc: U022EF6PV1B
sinisastankovic: U0110S67B44
Sinan-Altuntas: U01QX0N5EKU
slu125: U04Q5D7FU
smilesrg: U027YKFBY57
stas-lingoda: U02BGJ5DSCD
svichka: U0306LFBZL4
Taimoormk: U0289CN59RC
TamasSzigeti: U9TH7PNRY
theophileds: U01MJ68A9FW
tihomir-stefanov: UM331SVM0
TMD44: U02G8UCGQ3W
uaka: UKB01KAJ1
WojciechCendrzak: U02FL0K0412
kdaniel95: U02JKGA16G2
xDae: U02KEUEQ9HP
er1z: U03046V97D0
StefanGramadnikov: U02K91P8WL8
YoSoyElCapitan: U02DRAY8AUB
johnzuk: U037LDP4T7H
strezhi: U02JCJ92CTY
VovaYushka: U02S9NG3K5L
ozahorulia: U03C4549ULX
JyothiPrakash13: U03E15S9LCT
surya-talentship: U03BU2LHLH0
premkumar199131: U03BDCK1RQX
ragavendranramesh: U03BX7TJ7HS
rivaros: U02S9SH86HL
fatih-d: U02BKQPH1FD
vivekbaskaran24021: U03D3BLABEX
supreethdevm: U7EHJ9GCD
tomekknapczyk: U04P2EDMAPR
