<?php

declare(strict_types=1);

namespace Lingoda\ThinkingcapBundle\WebService\CourseManagement;

use Soap\Encoding\ClassMap\ClassMap;
use Soap\Encoding\ClassMap\ClassMapCollection;

class CourseManagementClassmap
{
    public static function types(): ClassMapCollection
    {
        return new ClassMapCollection(
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfCourse', Type\ServiceResultOfCourse::class),
            new ClassMap('http://www.thinkingcap.com/', 'Course', Type\Course::class),
            new ClassMap('http://www.thinkingcap.com/', 'LearningType', Type\LearningType::class),
            new ClassMap('http://www.thinkingcap.com/', 'LearningTypeCaptionInfo', Type\LearningTypeCaptionInfo::class),
            new ClassMap('http://www.thinkingcap.com/', 'AccreditationDetails', Type\AccreditationDetails::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfReference', Type\ArrayOfReference::class),
            new ClassMap('http://www.thinkingcap.com/', 'Reference', Type\Reference::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfAnyType', Type\ArrayOfAnyType::class),
            new ClassMap('http://www.thinkingcap.com/', 'Activity', Type\Activity::class),
            new ClassMap('http://www.thinkingcap.com/', 'ActivityTitleNode', Type\ActivityTitleNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ActivityDescriptionNode', Type\ActivityDescriptionNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'Schedule', Type\Schedule::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfString', Type\ArrayOfString::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfActivityNotification', Type\ArrayOfActivityNotification::class),
            new ClassMap('http://www.thinkingcap.com/', 'ActivityNotification', Type\ActivityNotification::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfAssignment', Type\ArrayOfAssignment::class),
            new ClassMap('http://www.thinkingcap.com/', 'Assignment', Type\Assignment::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCourseAssignment', Type\ArrayOfCourseAssignment::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseAssignment', Type\CourseAssignment::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCourseStylesheet', Type\ArrayOfCourseStylesheet::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseStylesheet', Type\CourseStylesheet::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCourseVersion', Type\ArrayOfCourseVersion::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseVersion', Type\CourseVersion::class),
            new ClassMap('http://www.thinkingcap.com/', 'ActivityMapVersion', Type\ActivityMapVersion::class),
            new ClassMap('http://www.thinkingcap.com/', 'FeedbackSection', Type\FeedbackSection::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfFeedbackQuestion', Type\ArrayOfFeedbackQuestion::class),
            new ClassMap('http://www.thinkingcap.com/', 'FeedbackQuestion', Type\FeedbackQuestion::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCourseNotification', Type\ArrayOfCourseNotification::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseNotification', Type\CourseNotification::class),
            new ClassMap('http://www.thinkingcap.com/', 'ActivityMap', Type\ActivityMap::class),
            new ClassMap('http://www.thinkingcap.com/', 'StudentRecord', Type\StudentRecord::class),
            new ClassMap('http://www.thinkingcap.com/', 'StudentActivityMap', Type\StudentActivityMap::class),
            new ClassMap('http://www.thinkingcap.com/', 'StudentActivityMapXml', Type\StudentActivityMapXml::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseAlternativePrice', Type\CourseAlternativePrice::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseSession', Type\CourseSession::class),
            new ClassMap('http://www.thinkingcap.com/', 'TrainingLocation', Type\TrainingLocation::class),
            new ClassMap('http://www.thinkingcap.com/', 'TimeZone', Type\TimeZone::class),
            new ClassMap('http://www.thinkingcap.com/', 'TimeZoneOffset', Type\TimeZoneOffset::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfSessionConnectedUser', Type\ArrayOfSessionConnectedUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'SessionConnectedUser', Type\SessionConnectedUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseTALoad', Type\CourseTALoad::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfLearningActivity', Type\ServiceResultOfLearningActivity::class),
            new ClassMap('http://www.thinkingcap.com/', 'LearningActivity', Type\LearningActivity::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCustomField', Type\ArrayOfCustomField::class),
            new ClassMap('http://www.thinkingcap.com/', 'CustomField', Type\CustomField::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfString1', Type\ArrayOfString1::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCourseSession', Type\ArrayOfCourseSession::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfLearningActivityCohort', Type\ArrayOfLearningActivityCohort::class),
            new ClassMap('http://www.thinkingcap.com/', 'LearningActivityCohort', Type\LearningActivityCohort::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfXmlDocument', Type\ServiceResultOfXmlDocument::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfXmlDocumentResult', Type\ServiceResultOfXmlDocumentResult::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfListOfLearningActivity', Type\ServiceResultOfListOfLearningActivity::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfLearningActivity', Type\ArrayOfLearningActivity::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfString', Type\ServiceResultOfString::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfListOfAssignment', Type\ServiceResultOfListOfAssignment::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfListOfStudentRecord', Type\ServiceResultOfListOfStudentRecord::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfStudentRecord', Type\ArrayOfStudentRecord::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfListOfLearningActivityRecord', Type\ServiceResultOfListOfLearningActivityRecord::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfLearningActivityRecord', Type\ArrayOfLearningActivityRecord::class),
            new ClassMap('http://www.thinkingcap.com/', 'LearningActivityRecord', Type\LearningActivityRecord::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfCustomField', Type\ServiceResultOfCustomField::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfListOfTrainingLocation', Type\ServiceResultOfListOfTrainingLocation::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfTrainingLocation', Type\ArrayOfTrainingLocation::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfTrainingLocation', Type\ServiceResultOfTrainingLocation::class),
            new ClassMap('http://www.thinkingcap.com/', 'TimeIntervalsList', Type\TimeIntervalsList::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfTimeInterval', Type\ArrayOfTimeInterval::class),
            new ClassMap('http://www.thinkingcap.com/', 'TimeInterval', Type\TimeInterval::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfBoolean', Type\ServiceResultOfBoolean::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfListOfUser', Type\ServiceResultOfListOfUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfUser', Type\ArrayOfUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'User', Type\User::class),
            new ClassMap('http://www.thinkingcap.com/', 'UserCustomFields', Type\UserCustomFields::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfDomainURLsCollection', Type\ArrayOfDomainURLsCollection::class),
            new ClassMap('http://www.thinkingcap.com/', 'DomainURLsCollection', Type\DomainURLsCollection::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfMail', Type\ArrayOfMail::class),
            new ClassMap('http://www.thinkingcap.com/', 'Mail', Type\Mail::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfMailFolder', Type\ArrayOfMailFolder::class),
            new ClassMap('http://www.thinkingcap.com/', 'MailFolder', Type\MailFolder::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfContact', Type\ArrayOfContact::class),
            new ClassMap('http://www.thinkingcap.com/', 'Contact', Type\Contact::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfRole', Type\ArrayOfRole::class),
            new ClassMap('http://www.thinkingcap.com/', 'Role', Type\Role::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfPermission', Type\ArrayOfPermission::class),
            new ClassMap('http://www.thinkingcap.com/', 'Permission', Type\Permission::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfProgram', Type\ArrayOfProgram::class),
            new ClassMap('http://www.thinkingcap.com/', 'Program', Type\Program::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramPOPurchaseInstructionsXmlNode', Type\ProgramPOPurchaseInstructionsXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationIntroXmlNode', Type\ProgramRegistrationIntroXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationDuplicateAccountInstrXmlNode', Type\ProgramRegistrationDuplicateAccountInstrXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationDisclaimerXmlNode', Type\ProgramRegistrationDisclaimerXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationConfirmationTextXmlNode', Type\ProgramRegistrationConfirmationTextXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationRequestConfirmationTextXmlNode', Type\ProgramRegistrationRequestConfirmationTextXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationConfirmationEmailXmlNode', Type\ProgramRegistrationConfirmationEmailXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationRequestEmailXmlNode', Type\ProgramRegistrationRequestEmailXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationRequestApprovalEmailXmlNode', Type\ProgramRegistrationRequestApprovalEmailXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationRequestDenialEmailXmlNode', Type\ProgramRegistrationRequestDenialEmailXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramUserDomainDisplayLabelXmlNode', Type\ProgramUserDomainDisplayLabelXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCourse', Type\ArrayOfCourse::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfListOfCourseSession', Type\ServiceResultOfListOfCourseSession::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfCourseSession', Type\ServiceResultOfCourseSession::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfCourseSeries', Type\ServiceResultOfCourseSeries::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseSeries', Type\CourseSeries::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfListOfCourseSeries', Type\ServiceResultOfListOfCourseSeries::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCourseSeries', Type\ArrayOfCourseSeries::class),
            new ClassMap('http://www.thinkingcap.com/', 'FindCourse', Type\FindCourse::class),
            new ClassMap('http://www.thinkingcap.com/', 'FindCourseResponse', Type\FindCourseResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityByID', Type\GetLearningActivityByID::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityByIDResponse', Type\GetLearningActivityByIDResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseByCode', Type\GetCourseByCode::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseByCodeResponse', Type\GetCourseByCodeResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetILTClassSizeDetailsXML', Type\GetILTClassSizeDetailsXML::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetILTClassSizeDetailsXMLResponse', Type\GetILTClassSizeDetailsXMLResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityByCode', Type\GetLearningActivityByCode::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityByCodeResponse', Type\GetLearningActivityByCodeResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetDomainLearningActivities', Type\GetDomainLearningActivities::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetDomainLearningActivitiesResponse', Type\GetDomainLearningActivitiesResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'ReserveSpotILT', Type\ReserveSpotILT::class),
            new ClassMap('http://www.thinkingcap.com/', 'ReserveSpotILTResponse', Type\ReserveSpotILTResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'AddLearningActivity', Type\AddLearningActivity::class),
            new ClassMap('http://www.thinkingcap.com/', 'AddLearningActivityResponse', Type\AddLearningActivityResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateLearningActivity', Type\UpdateLearningActivity::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateLearningActivityResponse', Type\UpdateLearningActivityResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'DeleteLearningActivity', Type\DeleteLearningActivity::class),
            new ClassMap('http://www.thinkingcap.com/', 'DeleteLearningActivityResponse', Type\DeleteLearningActivityResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateLearningActivityInfo', Type\UpdateLearningActivityInfo::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateLearningActivityInfoResponse', Type\UpdateLearningActivityInfoResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetCourseTAs', Type\SetCourseTAs::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetCourseTAsResponse', Type\SetCourseTAsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetCourseMarkedBy', Type\SetCourseMarkedBy::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetCourseMarkedByResponse', Type\SetCourseMarkedByResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseAssignmentsList', Type\GetCourseAssignmentsList::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseAssignmentsListResponse', Type\GetCourseAssignmentsListResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseAssignmentsXml', Type\GetCourseAssignmentsXml::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseAssignmentsXmlResponse', Type\GetCourseAssignmentsXmlResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseStudentsList', Type\GetCourseStudentsList::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseStudentsListResponse', Type\GetCourseStudentsListResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityStudentRecords', Type\GetLearningActivityStudentRecords::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityStudentRecordsResponse', Type\GetLearningActivityStudentRecordsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityStudentRecordsFiltered', Type\GetLearningActivityStudentRecordsFiltered::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityStudentRecordsFilteredResponse', Type\GetLearningActivityStudentRecordsFilteredResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityCustomFieldValues', Type\GetLearningActivityCustomFieldValues::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityCustomFieldValuesResponse', Type\GetLearningActivityCustomFieldValuesResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'ChangeLearningActivityActiveStatus', Type\ChangeLearningActivityActiveStatus::class),
            new ClassMap('http://www.thinkingcap.com/', 'ChangeLearningActivityActiveStatusResponse', Type\ChangeLearningActivityActiveStatusResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GenerateECommerceCourseToken', Type\GenerateECommerceCourseToken::class),
            new ClassMap('http://www.thinkingcap.com/', 'GenerateECommerceCourseTokenResponse', Type\GenerateECommerceCourseTokenResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'AddTrainingLocationWithTimeZone', Type\AddTrainingLocationWithTimeZone::class),
            new ClassMap('http://www.thinkingcap.com/', 'AddTrainingLocationWithTimeZoneResponse', Type\AddTrainingLocationWithTimeZoneResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'AddTrainingLocation', Type\AddTrainingLocation::class),
            new ClassMap('http://www.thinkingcap.com/', 'AddTrainingLocationResponse', Type\AddTrainingLocationResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetTrainingLocationsList', Type\GetTrainingLocationsList::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetTrainingLocationsListResponse', Type\GetTrainingLocationsListResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetTrainingLocation', Type\GetTrainingLocation::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetTrainingLocationResponse', Type\GetTrainingLocationResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'IsTrainingLocationAvailable', Type\IsTrainingLocationAvailable::class),
            new ClassMap('http://www.thinkingcap.com/', 'IsTrainingLocationAvailableResponse', Type\IsTrainingLocationAvailableResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseModeratorsList', Type\GetCourseModeratorsList::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseModeratorsListResponse', Type\GetCourseModeratorsListResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'AddCourseSession', Type\AddCourseSession::class),
            new ClassMap('http://www.thinkingcap.com/', 'AddCourseSessionResponse', Type\AddCourseSessionResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateCourseSession', Type\UpdateCourseSession::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateCourseSessionResponse', Type\UpdateCourseSessionResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseSessionsList', Type\GetCourseSessionsList::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseSessionsListResponse', Type\GetCourseSessionsListResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetILTCourseCurrentSession', Type\GetILTCourseCurrentSession::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetILTCourseCurrentSessionResponse', Type\GetILTCourseCurrentSessionResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'CreateCourseSeries', Type\CreateCourseSeries::class),
            new ClassMap('http://www.thinkingcap.com/', 'CreateCourseSeriesResponse', Type\CreateCourseSeriesResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityEquivalencyByID', Type\GetLearningActivityEquivalencyByID::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityEquivalencyByIDResponse', Type\GetLearningActivityEquivalencyByIDResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityEquivalencyByCode', Type\GetLearningActivityEquivalencyByCode::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLearningActivityEquivalencyByCodeResponse', Type\GetLearningActivityEquivalencyByCodeResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseSeriesList', Type\GetCourseSeriesList::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseSeriesListResponse', Type\GetCourseSeriesListResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetEquivalencyLearningActivities', Type\GetEquivalencyLearningActivities::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetEquivalencyLearningActivitiesResponse', Type\GetEquivalencyLearningActivitiesResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetAvailableCourses', Type\GetAvailableCourses::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetAvailableCoursesResponse', Type\GetAvailableCoursesResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'getLearningActivityDetails', Type\GetLearningActivityDetails::class),
            new ClassMap('http://www.thinkingcap.com/', 'getLearningActivityDetailsResponse', Type\GetLearningActivityDetailsResponse::class),
        );
    }

    public static function enums(): ClassMapCollection
    {
        return new ClassMapCollection(

        );
    }
}
