<?php

declare(strict_types=1);

namespace Lingoda\ThinkingcapBundle\WebService\LearnerManagement;

use Soap\Encoding\ClassMap\ClassMap;
use Soap\Encoding\ClassMap\ClassMapCollection;

class LearnerManagementClassmap
{
    public static function types(): ClassMapCollection
    {
        return new ClassMapCollection(
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfUserList', Type\ServiceResultOfUserList::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfUser', Type\ArrayOfUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'User', Type\User::class),
            new ClassMap('http://www.thinkingcap.com/', 'UserCustomFields', Type\UserCustomFields::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfDomainURLsCollection', Type\ArrayOfDomainURLsCollection::class),
            new ClassMap('http://www.thinkingcap.com/', 'DomainURLsCollection', Type\DomainURLsCollection::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfString', Type\ArrayOfString::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfMail', Type\ArrayOfMail::class),
            new ClassMap('http://www.thinkingcap.com/', 'Mail', Type\Mail::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfMailFolder', Type\ArrayOfMailFolder::class),
            new ClassMap('http://www.thinkingcap.com/', 'MailFolder', Type\MailFolder::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfContact', Type\ArrayOfContact::class),
            new ClassMap('http://www.thinkingcap.com/', 'Contact', Type\Contact::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfRole', Type\ArrayOfRole::class),
            new ClassMap('http://www.thinkingcap.com/', 'Role', Type\Role::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfPermission', Type\ArrayOfPermission::class),
            new ClassMap('http://www.thinkingcap.com/', 'Permission', Type\Permission::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfProgram', Type\ArrayOfProgram::class),
            new ClassMap('http://www.thinkingcap.com/', 'Program', Type\Program::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramPOPurchaseInstructionsXmlNode', Type\ProgramPOPurchaseInstructionsXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationIntroXmlNode', Type\ProgramRegistrationIntroXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationDuplicateAccountInstrXmlNode', Type\ProgramRegistrationDuplicateAccountInstrXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationDisclaimerXmlNode', Type\ProgramRegistrationDisclaimerXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationConfirmationTextXmlNode', Type\ProgramRegistrationConfirmationTextXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationRequestConfirmationTextXmlNode', Type\ProgramRegistrationRequestConfirmationTextXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationConfirmationEmailXmlNode', Type\ProgramRegistrationConfirmationEmailXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationRequestEmailXmlNode', Type\ProgramRegistrationRequestEmailXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationRequestApprovalEmailXmlNode', Type\ProgramRegistrationRequestApprovalEmailXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramRegistrationRequestDenialEmailXmlNode', Type\ProgramRegistrationRequestDenialEmailXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ProgramUserDomainDisplayLabelXmlNode', Type\ProgramUserDomainDisplayLabelXmlNode::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfAnyType', Type\ArrayOfAnyType::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCourse', Type\ArrayOfCourse::class),
            new ClassMap('http://www.thinkingcap.com/', 'Course', Type\Course::class),
            new ClassMap('http://www.thinkingcap.com/', 'LearningType', Type\LearningType::class),
            new ClassMap('http://www.thinkingcap.com/', 'LearningTypeCaptionInfo', Type\LearningTypeCaptionInfo::class),
            new ClassMap('http://www.thinkingcap.com/', 'AccreditationDetails', Type\AccreditationDetails::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfReference', Type\ArrayOfReference::class),
            new ClassMap('http://www.thinkingcap.com/', 'Reference', Type\Reference::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfAssignment', Type\ArrayOfAssignment::class),
            new ClassMap('http://www.thinkingcap.com/', 'Assignment', Type\Assignment::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCourseAssignment', Type\ArrayOfCourseAssignment::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseAssignment', Type\CourseAssignment::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCourseStylesheet', Type\ArrayOfCourseStylesheet::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseStylesheet', Type\CourseStylesheet::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCourseVersion', Type\ArrayOfCourseVersion::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseVersion', Type\CourseVersion::class),
            new ClassMap('http://www.thinkingcap.com/', 'ActivityMapVersion', Type\ActivityMapVersion::class),
            new ClassMap('http://www.thinkingcap.com/', 'FeedbackSection', Type\FeedbackSection::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfFeedbackQuestion', Type\ArrayOfFeedbackQuestion::class),
            new ClassMap('http://www.thinkingcap.com/', 'FeedbackQuestion', Type\FeedbackQuestion::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCourseNotification', Type\ArrayOfCourseNotification::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseNotification', Type\CourseNotification::class),
            new ClassMap('http://www.thinkingcap.com/', 'ActivityMap', Type\ActivityMap::class),
            new ClassMap('http://www.thinkingcap.com/', 'TimeZone', Type\TimeZone::class),
            new ClassMap('http://www.thinkingcap.com/', 'TimeZoneOffset', Type\TimeZoneOffset::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseAlternativePrice', Type\CourseAlternativePrice::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseSession', Type\CourseSession::class),
            new ClassMap('http://www.thinkingcap.com/', 'TrainingLocation', Type\TrainingLocation::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfSessionConnectedUser', Type\ArrayOfSessionConnectedUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'SessionConnectedUser', Type\SessionConnectedUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'CourseTALoad', Type\CourseTALoad::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfListOfServiceUser', Type\ServiceResultOfListOfServiceUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfServiceUser', Type\ArrayOfServiceUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceUser', Type\ServiceUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfCustomField', Type\ArrayOfCustomField::class),
            new ClassMap('http://www.thinkingcap.com/', 'CustomField', Type\CustomField::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfString1', Type\ArrayOfString1::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfDomain', Type\ArrayOfDomain::class),
            new ClassMap('http://www.thinkingcap.com/', 'Domain', Type\Domain::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfString', Type\ServiceResultOfString::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfListOfServiceSupervisor', Type\ServiceResultOfListOfServiceSupervisor::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfServiceSupervisor', Type\ArrayOfServiceSupervisor::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceSupervisor', Type\ServiceSupervisor::class),
            new ClassMap('http://www.thinkingcap.com/', 'SupervisorType', Type\SupervisorType::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfServiceUser', Type\ServiceResultOfServiceUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfUser', Type\ServiceResultOfUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfStudentRecordList', Type\ServiceResultOfStudentRecordList::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfStudentRecord', Type\ArrayOfStudentRecord::class),
            new ClassMap('http://www.thinkingcap.com/', 'StudentRecord', Type\StudentRecord::class),
            new ClassMap('http://www.thinkingcap.com/', 'StudentActivityMap', Type\StudentActivityMap::class),
            new ClassMap('http://www.thinkingcap.com/', 'StudentActivityMapXml', Type\StudentActivityMapXml::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfStudentRecord', Type\ServiceResultOfStudentRecord::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfLearningActivityRecord', Type\ServiceResultOfLearningActivityRecord::class),
            new ClassMap('http://www.thinkingcap.com/', 'LearningActivityRecord', Type\LearningActivityRecord::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfListOfLearningActivityRecord', Type\ServiceResultOfListOfLearningActivityRecord::class),
            new ClassMap('http://www.thinkingcap.com/', 'ArrayOfLearningActivityRecord', Type\ArrayOfLearningActivityRecord::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfBoolean', Type\ServiceResultOfBoolean::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfXmlDocument', Type\ServiceResultOfXmlDocument::class),
            new ClassMap('http://www.thinkingcap.com/', 'ServiceResultOfXmlDocumentResult', Type\ServiceResultOfXmlDocumentResult::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetAllUsers', Type\GetAllUsers::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetAllUsersResponse', Type\GetAllUsersResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetDomainUsers', Type\GetDomainUsers::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetDomainUsersResponse', Type\GetDomainUsersResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'RegisterUser', Type\RegisterUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'RegisterUserResponse', Type\RegisterUserResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'RegisterBulkUser', Type\RegisterBulkUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'RegisterBulkUserResponse', Type\RegisterBulkUserResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateUser', Type\UpdateUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateUserResponse', Type\UpdateUserResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateUserMetadataValues', Type\UpdateUserMetadataValues::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateUserMetadataValuesResponse', Type\UpdateUserMetadataValuesResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateUserProfile', Type\UpdateUserProfile::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateUserProfileResponse', Type\UpdateUserProfileResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateStudentSupervisors', Type\UpdateStudentSupervisors::class),
            new ClassMap('http://www.thinkingcap.com/', 'UpdateStudentSupervisorsResponse', Type\UpdateStudentSupervisorsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetSupervisorUsers', Type\GetSupervisorUsers::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetSupervisorUsersResponse', Type\GetSupervisorUsersResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetUserSupervisors', Type\GetUserSupervisors::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetUserSupervisorsResponse', Type\GetUserSupervisorsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetUserByID', Type\GetUserByID::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetUserByIDResponse', Type\GetUserByIDResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetUserByEmail', Type\GetUserByEmail::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetUserByEmailResponse', Type\GetUserByEmailResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'FindUserIDByEmail', Type\FindUserIDByEmail::class),
            new ClassMap('http://www.thinkingcap.com/', 'FindUserIDByEmailResponse', Type\FindUserIDByEmailResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetUserByUserName', Type\GetUserByUserName::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetUserByUserNameResponse', Type\GetUserByUserNameResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'FindUserIDByUserName', Type\FindUserIDByUserName::class),
            new ClassMap('http://www.thinkingcap.com/', 'FindUserIDByUserNameResponse', Type\FindUserIDByUserNameResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetUsersByScreenName', Type\GetUsersByScreenName::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetUsersByScreenNameResponse', Type\GetUsersByScreenNameResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetUsersByCustomField', Type\GetUsersByCustomField::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetUsersByCustomFieldResponse', Type\GetUsersByCustomFieldResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'FindUserIDByCustomField', Type\FindUserIDByCustomField::class),
            new ClassMap('http://www.thinkingcap.com/', 'FindUserIDByCustomFieldResponse', Type\FindUserIDByCustomFieldResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'DeleteUser', Type\DeleteUser::class),
            new ClassMap('http://www.thinkingcap.com/', 'DeleteUserResponse', Type\DeleteUserResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'DeleteUserByLookup', Type\DeleteUserByLookup::class),
            new ClassMap('http://www.thinkingcap.com/', 'DeleteUserByLookupResponse', Type\DeleteUserByLookupResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'AddUserToDomain', Type\AddUserToDomain::class),
            new ClassMap('http://www.thinkingcap.com/', 'AddUserToDomainResponse', Type\AddUserToDomainResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'AddUserToDomainWithEnrollments', Type\AddUserToDomainWithEnrollments::class),
            new ClassMap('http://www.thinkingcap.com/', 'AddUserToDomainWithEnrollmentsResponse', Type\AddUserToDomainWithEnrollmentsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetUserActive', Type\SetUserActive::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetUserActiveResponse', Type\SetUserActiveResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetUserActiveByLookup', Type\SetUserActiveByLookup::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetUserActiveByLookupResponse', Type\SetUserActiveByLookupResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetStudentTranscript', Type\GetStudentTranscript::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetStudentTranscriptResponse', Type\GetStudentTranscriptResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'EnrollStudentWithDetails', Type\EnrollStudentWithDetails::class),
            new ClassMap('http://www.thinkingcap.com/', 'EnrollStudentWithDetailsResponse', Type\EnrollStudentWithDetailsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'EnrollStudentQueued', Type\EnrollStudentQueued::class),
            new ClassMap('http://www.thinkingcap.com/', 'EnrollStudentQueuedResponse', Type\EnrollStudentQueuedResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'EnrollStudent', Type\EnrollStudent::class),
            new ClassMap('http://www.thinkingcap.com/', 'EnrollStudentResponse', Type\EnrollStudentResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'EnrollStudentReservation', Type\EnrollStudentReservation::class),
            new ClassMap('http://www.thinkingcap.com/', 'EnrollStudentReservationResponse', Type\EnrollStudentReservationResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'StudentSelfEnroll', Type\StudentSelfEnroll::class),
            new ClassMap('http://www.thinkingcap.com/', 'StudentSelfEnrollResponse', Type\StudentSelfEnrollResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'WithdrawStudent', Type\WithdrawStudent::class),
            new ClassMap('http://www.thinkingcap.com/', 'WithdrawStudentResponse', Type\WithdrawStudentResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'MarkStudentSession', Type\MarkStudentSession::class),
            new ClassMap('http://www.thinkingcap.com/', 'MarkStudentSessionResponse', Type\MarkStudentSessionResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetStudentLPDetails', Type\GetStudentLPDetails::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetStudentLPDetailsResponse', Type\GetStudentLPDetailsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetRecordDetails', Type\GetRecordDetails::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetRecordDetailsResponse', Type\GetRecordDetailsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetStudentLearningActivityRecordDetails', Type\GetStudentLearningActivityRecordDetails::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetStudentLearningActivityRecordDetailsResponse', Type\GetStudentLearningActivityRecordDetailsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetStudentLearningActivityRecords', Type\GetStudentLearningActivityRecords::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetStudentLearningActivityRecordsResponse', Type\GetStudentLearningActivityRecordsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetAllStudentLearningActivityRecords', Type\GetAllStudentLearningActivityRecords::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetAllStudentLearningActivityRecordsResponse', Type\GetAllStudentLearningActivityRecordsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCompletedStudentRecordsWithPreset', Type\GetCompletedStudentRecordsWithPreset::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCompletedStudentRecordsWithPresetResponse', Type\GetCompletedStudentRecordsWithPresetResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetRecordDetails', Type\SetRecordDetails::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetRecordDetailsResponse', Type\SetRecordDetailsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'ExtendRecordDueDate', Type\ExtendRecordDueDate::class),
            new ClassMap('http://www.thinkingcap.com/', 'ExtendRecordDueDateResponse', Type\ExtendRecordDueDateResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GenerateTimedSeed', Type\GenerateTimedSeed::class),
            new ClassMap('http://www.thinkingcap.com/', 'GenerateTimedSeedResponse', Type\GenerateTimedSeedResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'ValidateTimedSeed', Type\ValidateTimedSeed::class),
            new ClassMap('http://www.thinkingcap.com/', 'ValidateTimedSeedResponse', Type\ValidateTimedSeedResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'MergeStudentTranscripts', Type\MergeStudentTranscripts::class),
            new ClassMap('http://www.thinkingcap.com/', 'MergeStudentTranscriptsResponse', Type\MergeStudentTranscriptsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetStudentAvailableCourses', Type\GetStudentAvailableCourses::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetStudentAvailableCoursesResponse', Type\GetStudentAvailableCoursesResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseCompletionStatusByDateRange', Type\GetCourseCompletionStatusByDateRange::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetCourseCompletionStatusByDateRangeResponse', Type\GetCourseCompletionStatusByDateRangeResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'getLearningActivityListEnrollments', Type\GetLearningActivityListEnrollments::class),
            new ClassMap('http://www.thinkingcap.com/', 'getLearningActivityListEnrollmentsResponse', Type\GetLearningActivityListEnrollmentsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'getLearningActivityListEnrollmentsTruncated', Type\GetLearningActivityListEnrollmentsTruncated::class),
            new ClassMap('http://www.thinkingcap.com/', 'getLearningActivityListEnrollmentsTruncatedResponse', Type\GetLearningActivityListEnrollmentsTruncatedResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLMSUserAutoLoginURL', Type\GetLMSUserAutoLoginURL::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLMSUserAutoLoginURLResponse', Type\GetLMSUserAutoLoginURLResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLMSUserAutoLoginURLByUsername', Type\GetLMSUserAutoLoginURLByUsername::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetLMSUserAutoLoginURLByUsernameResponse', Type\GetLMSUserAutoLoginURLByUsernameResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetActiveDirectorySynchSettings', Type\GetActiveDirectorySynchSettings::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetActiveDirectorySynchSettingsResponse', Type\GetActiveDirectorySynchSettingsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'TestPost', Type\TestPost::class),
            new ClassMap('http://www.thinkingcap.com/', 'TestPostResponse', Type\TestPostResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetSCORMDetails', Type\GetSCORMDetails::class),
            new ClassMap('http://www.thinkingcap.com/', 'GetSCORMDetailsResponse', Type\GetSCORMDetailsResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetSCORMValues', Type\SetSCORMValues::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetSCORMValuesResponse', Type\SetSCORMValuesResponse::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetFeedbackCompleted', Type\SetFeedbackCompleted::class),
            new ClassMap('http://www.thinkingcap.com/', 'SetFeedbackCompletedResponse', Type\SetFeedbackCompletedResponse::class),
        );
    }

    public static function enums(): ClassMapCollection
    {
        return new ClassMapCollection(

        );
    }
}
