name: php-packages
permissions: write-all
on: [pull_request, push]
env:
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    GITHUB_TOKEN: ${{ github.token }}

jobs:
    prepare:
        runs-on: ubuntu-latest
        outputs:
            composercachedir: ${{ steps.composercache.outputs.dir }}
            slackuser: ${{ steps.slack.outputs.user }}
        steps:
            # Cancel previous runs of the same branch
            - name: cancel
              uses: styfle/cancel-workflow-action@0.11.0

            - name: checkout
              uses: actions/checkout@v3

            - name: composer-cache
              id: composercache
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: slack
              id: slack
              run: |
                  export SLACKUSER=$(grep "${{ github.actor }}" .github/developers.yaml | awk '{print $2}')

                  if [ -z "$SLACKUSER" ]; then
                      # Fall back to #development
                      export SLACKUSER=C0A3LKS87
                  fi

                  echo "user=$SLACKUSER" >> $GITHUB_OUTPUT

    tests:
        runs-on: ubuntu-latest
        needs: [prepare]
        strategy:
            matrix:
                install-args: ['', --prefer-lowest]
            fail-fast: false
        env:
            # List deprecations and fail on self ones
            SYMFONY_DEPRECATIONS_HELPER: 'max[self]=0&verbose=0'
        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@2.24.0
              with:
                  php-version: '8.1'
                  extensions: apcu, redis

            - name: composer-cache
              uses: actions/cache@v3.2.6
              with:
                  path: ${{ needs.prepare.outputs.composercachedir }}
                  key: composer-phppkg-${{ hashFiles('composer.lock') }}
                  restore-keys: composer-phppkg-

            - name: install
              run: |
                  composer install --no-interaction --no-progress --prefer-dist -d linters
                  linters/scripts/php-packages-install.sh ${{ matrix.install-args }}

            - name: phpspec
              if: ${{ !cancelled() }}
              run: |
                  linters/scripts/php-packages-phpspec.sh

            - name: phpstan-cache
              if: ${{ !cancelled() }}
              uses: actions/cache@v3.2.6
              with:
                  key: phpstan-phppkg-${{ github.ref }}-${{ github.sha }}
                  path: linters/.phpstan-cache
                  restore-keys: |
                      phpstan-phppkg-${{ github.ref }}-
                      phpstan-phppkg-

            - name: phpstan
              if: ${{ !cancelled() }}
              run: |
                  linters/scripts/php-packages-phpstan.sh

            - name: phpunit
              if: ${{ !cancelled() }}
              env:
                  # List deprecations and fail on self ones
                  SYMFONY_DEPRECATIONS_HELPER: 'max[self]=0&verbose=0'
              run: |
                  linters/scripts/php-packages-phpunit.sh

            - name: slack
              if: failure()
              uses: 8398a7/action-slack@v3.15.1
              with:
                  status: ${{ job.status }}
                  fields: ref,author
                  text: '<https://github.com/lingoda/lingoda/actions/runs/${{ github.run_id }}|Failed stan/spec> :shit:'
                  author_name: ${{ job.name }}
                  channel: ${{ needs.prepare.outputs.slackuser }}
